### ISSUE TITLE
Connecting slow (Windows)

### ISSUE THREAD

**Issue by thekid** [xp-framework/networking#2]
This here:

``` sh
$ xp -w "(new \util\profiling\Timer())->measure(function() {
  stream_socket_client('tcp://localhost:3306', $n, $e, 2.0, STREAM_CLIENT_CONNECT);
})->elapsedTime()"
1.0057129859924
```

...is roughly **an entire second slower** than:

``` sh
$ xp -w "(new \util\profiling\Timer())->measure(function() {
  $ip= gethostbyname('localhost');
  stream_socket_client('tcp://'.$ip.':3306', $n, $e, 2.0, STREAM_CLIENT_CONNECT);
})->elapsedTime()"
0.0055131912231445
```

Using google.com as address there is no difference, both are around 0.03618311882019 seconds.

**Comment by thekid** [comment]
This does not occur on Linux

**Comment by thekid** [comment]
Looks as if it's related to how [`php_network_connect_socket_to_host()`](https://github.com/php/php-src/blob/3994a70b910841492b03da165c691f36b82b2f72/main/network.c#L788) handles connecting: It attempts to connect to all addresses returned by [`php_network_getaddresses()`](https://github.com/php/php-src/blob/3994a70b910841492b03da165c691f36b82b2f72/main/network.c#L169).  On Windows systems, `getaddrinfo("localhost")` will most probably also return an IPv6 address, which PHP then tries to connect to first (and fails doing so).

> In order to support both IPV4 and IPV6 (at least on Windows) localhost is getting mapped to two IP addresses

_Source: http://blogs.iis.net/donraman/php-5-3-and-mysql-connectivity-problem_

**Comment by thekid** [comment]
Something which works well on both platforms for IP addresses as well as host names is performing a `gethostbyname($host)` before passing the value to `stream_socket_client()`:

```php
  if ('[' === $host{0}) {
    // IPv6
  } else if (4 === sscanf($host, '%d.%d.%d.%d')) {
    // IPv4
  } else {
    $host= gethostbyname($host);
  }

  $s= stream_socket_client('tcp://'.$host.':3306', $n, $e, 2.0, STREAM_CLIENT_CONNECT);
```

**Comment by thekid** [comment]
My idea would be to force IPv4 for localhost and make people use `[::1]` if they want the IPv6 versions. Seems like a more sensible default to me given that most services will still listen on IPv4 addresses:

``` diff
diff --git a/ChangeLog.md b/ChangeLog.md
index 871b4d9..6c9f715 100644
--- a/ChangeLog.md
+++ b/ChangeLog.md
@@ -3,6 +3,11 @@ Networking changelog

 ## ?.?.? / ????-??-??

+## 8.0.0 / 2016-07-23
+
+* Changed `localhost` to always refer to `127.0.0.1`. If you need to
+  connect using IPv6, use `::1`. See issue #2 for an explanation.
+  (@thekid)
 * Allowed binding servers to IPv6 addresses - @thekid

 ## 7.1.0 / 2016-04-04
diff --git a/src/main/php/peer/Socket.class.php b/src/main/php/peer/Socket.class.php
index 6560bfe..c260400 100755
--- a/src/main/php/peer/Socket.class.php
+++ b/src/main/php/peer/Socket.class.php
@@ -126,9 +126,11 @@ class Socket extends \lang\Object implements \io\Channel {
    */
   public function connect($timeout= 2.0) {
     if ($this->isConnected()) return true;
-
+
+    // Force IPv4 for localhost, see https://github.com/xp-framework/networking/issues/2
+    $host= (string)$this->host;
     if (!$this->_sock= stream_socket_client(
-      $this->_prefix.(string)$this->host.':'.$this->port,
+      $this->_prefix.('localhost' === $host ? '127.0.0.1' : $host).':'.$this->port,
       $errno,
       $errstr,
       $timeout,
```

@kiesel What do you think?

**Comment by kiesel** [comment]
Well this sounds like a pragmatic solution, though it is not 100% drop in & safe. There's two things to consider:
1. `localhost` might be resolved through DNS - eg. `localhost.<search.domain>` might exist and no local localhost entry might be present in `/etc/hosts`.
2. `localhost` might be "bound" to a different IP than `127.0.0.1` - all of `127.x.y.z` all are loopback addresses.

I'd consider both cases as not practically relevant, though. It still feels like a hack:)

**Comment by thekid** [comment]
Thanks for the feedback. Decided to go for it with anyway, but with a major release

**Comment by thekid** [comment]
This causes the following problem when talking to localhost via SSL/TLS:

```
stream_socket_enable_crypto(): Peer certificate CN=`localhost' did not match expected CN=`127.0.0.1'
```
